parameters:
- name: task
  type: string
  default: ''
- name: directoryPath
  type: string

steps: 
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '**'
    TargetFolder: '${{ parameters.directoryPath }}/'

- task: Gradle@2
  inputs:
    gradleWrapperFile: ${{ parameters.directoryPath }}/gradlew
    workingDirectory: '${{ parameters.directoryPath }}/'
    options: '-x jar -x javadoc -x javadocJar -x compileJava -x processResources -x classes -x sourceJar'
    tasks: ${{ parameters.task }}
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
