steps:
- pwsh: 'Invoke-WebRequest -Uri https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16%2B36/OpenJDK16-jdk_x64_windows_hotspot_16_36.zip -OutFile OpenJDK.zip'
  displayName: 'Download JDK'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '16'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'OpenJDK.zip'
    jdkDestinationDirectory: 'binaries'