parameters:
- name: gitConnection
  type: string
  default: ''
- name: directoryPath
  type: string

steps: 
- task: PowerShell@2
  inputs:
    filePath: '${{ parameters.directoryPath }}/Scripts/getLatestVersion.ps1'
    arguments: '-propertiesPath "${{ parameters.directoryPath }}/gradle.properties"'
    pwsh: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: ${{ parameters.gitConnection }}
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(VERSION_STRING)'
    assets: |
      !**/**
      $(Build.ArtifactStagingDirectory)/*
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
