buildscript {
    repositories {
        google()
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.gradle:gradle-enterprise-gradle-plugin:3.19.2"
        classpath "com.android.tools.build:gradle:9.3.1"
        classpath "com.github.ben-manes:gradle-versions-plugin:0.54.0"
    }
}

repositories {
    google()
    gradlePluginPortal()
    mavenCentral()
}

apply plugin: "com.android.library"
apply plugin: "com.github.ben-manes.versions"

android {
    namespace "com.microsoft.graph"

    compileSdkVersion 37

    defaultConfig {
        versionCode 1
        versionName "1.0"
        minSdkVersion 26
        targetSdkVersion 37
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        baseline = file("lint-baseline.xml")
    }

    lintOptions {
        textOutput "stdout"
        checkAllWarnings true
        warningsAsErrors true
        lintConfig file("lint.xml")
        disable 'AndroidGradlePluginVersion' // We will not be upgrading gradle to version 9 as it does not support our minimum required version of jdk8
    }

    sourceSets {
        main {
            java.srcDirs = ['../src/main/java']
            res.srcDirs = ['../src/main/java']
            manifest.srcFile 'AndroidManifest.xml'
        }
        androidTest {
            setRoot '../src/test'
        }
    }
}


dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'

    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
    implementation 'com.auth0:jwks-rsa:0.24.1'

    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'com.azure:azure-core:1.58.1'

    api 'com.microsoft.kiota:microsoft-kiota-abstractions:1.9.3'
    api 'com.microsoft.kiota:microsoft-kiota-authentication-azure:1.9.3'
    implementation 'com.microsoft.kiota:microsoft-kiota-http-okHttp:1.9.3'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-json:1.9.3'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-text:1.9.3'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-form:1.9.3'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-multipart:1.9.3'
}

