trigger: none
pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily builds
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
  settings:
    networkIsolationPolicy: Permissive
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    featureFlags:
      java:
        internalModuleProxy:
          enabled: true
    networkIsolation:
      overrideAllowRules:
        - host: repo.maven.apache.org
          port: 443
          protocols:
            - https
        - host: plugins.gradle.org
          port: 443
          protocols:
            - https
        - host: services.gradle.org
          port: 443
          protocols:
            - https
        - host: repo1.maven.org
          port: 443
          protocols:
            - https
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      credscan:
        enabled: true
      policheck:
        enabled: true
      binskim:
        enabled: true
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build Java Core SDK
            steps:
              - checkout: self
                submodules: recursive

              - script: |
                  sed -i "/com.github.spotbugs/d" build.gradle
                  sed -i "/org.sonarqube/d" build.gradle
                  sed -i "/spotbugsMain/,/^}/d" build.gradle
                  sed -i "/spotbugsTest/,/^}/d" build.gradle
                  sed -i "/sonarqube {/,/^}/d" build.gradle
                displayName: Remove code analysis plugins (not available in network-isolated agents)

              - task: Gradle@4
                displayName: Build and Test SDK
                inputs:
                  gradleWrapperFile: 'gradlew'
                  workingDirectory: '$(Build.SourcesDirectory)'
                  tasks: 'assemble test'
                  options: '--no-daemon'
                  publishJUnitResults: true
                  testResultsFiles: '**/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  jdkVersionOption: '1.17'
                  jdkArchitectureOption: 'x64'
