name: Git Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  Git_Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          workflow: build-and-publish.yml
          workflow_conclusion: success
          branch: master
          event: push
          name: drop
          path: drop
      - name: Github Release
        uses: anton-yurchenko/git-release@v6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
            drop/build/**/*.jar
