name: Git Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  Git_Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: build-and-publish.yml
          workflow_conclusion: success
          branch: main
          event: push
          name: drop
          path: drop
      - name: Github Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          files: |
            drop/build/**/*.jar
